name: smart_net_firmware_loader
description: "Firmware Loader Tool for SmartNet Solution."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  flutter_libserialport: ^0.3.0
  libserialport: ^0.3.0+1
  path_provider: ^2.1.2
  intl: ^0.18.1
  uuid: ^4.0.0
  window_manager: ^0.3.7
  cupertino_icons: ^1.0.8
  path: ^1.8.0
  http: ^1.4.0
  synchronized: ^3.3.1
  crypto: any
  cli_util: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#F5F5F5"
    theme_color: "#1976D2"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
  linux:
    generate: true
    image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app_icon.png
    - assets/arduino-cli/
    - assets/arduino-cli-linux/
    - assets/arduino-cli-macos/
